name: digital_pathsala
description: A Flutter project for login, registration, dashboard, and attendance
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0" # Compatible with Flutter 3.24.3

dependencies:
  flutter:
    sdk: flutter

  # Firebase packages
  firebase_core: ^3.4.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_spinkit: ^5.2.0

  # UI & utilities
  cupertino_icons: ^1.0.6
  provider: ^6.1.2

  # Date formatting
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

  # Add flutter_launcher_icons
  flutter_launcher_icons: ^0.10.0

flutter:
  uses-material-design: true
  assets:
    - assets/teacherphoto.jpeg

# Configuration for launcher icon
flutter_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.jpeg"
